import { ListView } from "std-widgets.slint";

export struct PdfFile {
    title: string,
    hash: string,
}

export component AppWindow inherits Window {
    in property <[PdfFile]> pdfs;
    in property <image> pdf_page;

    width: 800px;
    height: 200px;
    ListView {
        for pdf in pdfs: Text {
            text: pdf.hash;
        }
    }

    Image {
        source: pdf_page;
        width: 800px;
        height: 1000px;
    }
}
